version: "3.1"

services:
  db:
    container_name: postgres-db
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

  web:
    container_name: salary-calc-web
    build: .
    restart: "always"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static/:/code/static/
      - ./media/:/code/media/
    links:
      - db
    env_file: .env
    depends_on:
      - db

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: nginx-proxy