from django.core.management.base import BaseCommand
from django.db import transaction
from core.models import Year, Month, WorkCalendar

class Command(BaseCommand):
    help = 'Populate WorkCalendar data'

    def handle(self, *args, **options):
        months = {
            i: Month.objects.filter(month_number=i).first()
            for i in range(1, 13)
        }

        years = {
            i: Year.objects.filter(year_value=i).first()
            for i in range(2023, 2024)
        }


        if not WorkCalendar.objects.exists():
            if all(months.values()) and all(years.values()):
                data = [
                    {
                        'year': years[2023],
                        'month': months[1],
                        'monthly_work_hour': 143,
                        'group_a_general_work_hour': 176,
                        'group_a_daytime_work_hour': 120,
                        'group_a_nighttime_work_hour': 56,
                        'group_a_holiday_work_hour': 0,
                        'group_b_general_work_hour': 168,
                        'group_b_daytime_work_hour': 117,
                        'group_b_nighttime_work_hour': 51,
                        'group_b_holiday_work_hour': 0,
                        'group_c_general_work_hour': 173,
                        'group_c_daytime_work_hour': 119,
                        'group_c_nighttime_work_hour': 54,
                        'group_c_holiday_work_hour': 0,
                        'group_d_general_work_hour': 165,
                        'group_d_daytime_work_hour': 109,
                        'group_d_nighttime_work_hour': 56,
                        'group_d_holiday_work_hour': 0,
                    },
                    {
                        'year': years[2023],
                        'month': months[2],
                        'monthly_work_hour': 160,
                        'group_a_general_work_hour': 154,
                        'group_a_daytime_work_hour': 105,
                        'group_a_nighttime_work_hour': 49,
                        'group_a_holiday_work_hour': 0,
                        'group_b_general_work_hour': 154,
                        'group_b_daytime_work_hour': 105,
                        'group_b_nighttime_work_hour': 49,
                        'group_b_holiday_work_hour': 0,
                        'group_c_general_work_hour': 154,
                        'group_c_daytime_work_hour': 105,
                        'group_c_nighttime_work_hour': 49,
                        'group_c_holiday_work_hour': 0,
                        'group_d_general_work_hour': 154,
                        'group_d_daytime_work_hour': 105,
                        'group_d_nighttime_work_hour': 49,
                        'group_d_holiday_work_hour': 0,
                    },
                    {
                        'year': years[2023],
                        'month': months[3],
                        'monthly_work_hour': 135,
                        'group_a_general_work_hour': 168,
                        'group_a_daytime_work_hour': 117,
                        'group_a_nighttime_work_hour': 51,
                        'group_a_holiday_work_hour': 5,
                        'group_b_general_work_hour': 173,
                        'group_b_daytime_work_hour': 119,
                        'group_b_nighttime_work_hour': 54,
                        'group_b_holiday_work_hour': 0,
                        'group_c_general_work_hour': 165,
                        'group_c_daytime_work_hour': 109,
                        'group_c_nighttime_work_hour': 56,
                        'group_c_holiday_work_hour': 14,
                        'group_d_general_work_hour': 176,
                        'group_d_daytime_work_hour': 120,
                        'group_d_nighttime_work_hour': 56,
                        'group_d_holiday_work_hour': 0,
                    },
                    {
                        'year': years[2023],
                        'month': months[4],
                        'monthly_work_hour': 143,
                        'group_a_general_work_hour': 162,
                        'group_a_daytime_work_hour': 108,
                        'group_a_nighttime_work_hour': 54,
                        'group_a_holiday_work_hour': 0,
                        'group_b_general_work_hour': 165,
                        'group_b_daytime_work_hour': 109,
                        'group_b_nighttime_work_hour': 56,
                        'group_b_holiday_work_hour': 0,
                        'group_c_general_work_hour': 168,
                        'group_c_daytime_work_hour': 117,
                        'group_c_nighttime_work_hour': 51,
                        'group_c_holiday_work_hour': 0,
                        'group_d_general_work_hour': 165,
                        'group_d_daytime_work_hour': 116,
                        'group_d_nighttime_work_hour': 49,
                        'group_d_holiday_work_hour': 0,
                    },
                    {
                        'year': years[2023],
                        'month': months[5],
                        'monthly_work_hour': 167,
                        'group_a_general_work_hour': 176,
                        'group_a_daytime_work_hour': 120,
                        'group_a_nighttime_work_hour': 56,
                        'group_a_holiday_work_hour': 2,
                        'group_b_general_work_hour': 168,
                        'group_b_daytime_work_hour': 117,
                        'group_b_nighttime_work_hour': 51,
                        'group_b_holiday_work_hour': 7,
                        'group_c_general_work_hour': 173,
                        'group_c_daytime_work_hour': 119,
                        'group_c_nighttime_work_hour': 54,
                        'group_c_holiday_work_hour': 5,
                        'group_d_general_work_hour': 165,
                        'group_d_daytime_work_hour': 109,
                        'group_d_nighttime_work_hour': 56,
                        'group_d_holiday_work_hour': 14,
                    },
                    {
                        'year': years[2023],
                        'month': months[6],
                        'monthly_work_hour': 142,
                        'group_a_general_work_hour': 165,
                        'group_a_daytime_work_hour': 116,
                        'group_a_nighttime_work_hour': 49,
                        'group_a_holiday_work_hour': 0,
                        'group_b_general_work_hour': 162,
                        'group_b_daytime_work_hour': 108,
                        'group_b_nighttime_work_hour': 54,
                        'group_b_holiday_work_hour': 2,
                        'group_c_general_work_hour': 165,
                        'group_c_daytime_work_hour': 109,
                        'group_c_nighttime_work_hour': 56,
                        'group_c_holiday_work_hour': 0,
                        'group_d_general_work_hour': 168,
                        'group_d_daytime_work_hour': 117,
                        'group_d_nighttime_work_hour': 51,
                        'group_d_holiday_work_hour': 0,
                    },
                    {
                        'year': years[2023],
                        'month': months[7],
                        'monthly_work_hour': 168,
                        'group_a_general_work_hour': 165,
                        'group_a_daytime_work_hour': 109,
                        'group_a_nighttime_work_hour': 56,
                        'group_a_holiday_work_hour': 0,
                        'group_b_general_work_hour': 176,
                        'group_b_daytime_work_hour': 120,
                        'group_b_nighttime_work_hour': 56,
                        'group_b_holiday_work_hour': 0,
                        'group_c_general_work_hour': 168,
                        'group_c_daytime_work_hour': 117,
                        'group_c_nighttime_work_hour': 51,
                        'group_c_holiday_work_hour': 0,
                        'group_d_general_work_hour': 173,
                        'group_d_daytime_work_hour': 119,
                        'group_d_nighttime_work_hour': 54,
                        'group_d_holiday_work_hour': 0,
                    },
                    {
                        'year': years[2023],
                        'month': months[8],
                        'monthly_work_hour': 184,
                        'group_a_general_work_hour': 176,
                        'group_a_daytime_work_hour': 120,
                        'group_a_nighttime_work_hour': 56,
                        'group_a_holiday_work_hour': 0,
                        'group_b_general_work_hour': 168,
                        'group_b_daytime_work_hour': 117,
                        'group_b_nighttime_work_hour': 51,
                        'group_b_holiday_work_hour': 0,
                        'group_c_general_work_hour': 173,
                        'group_c_daytime_work_hour': 119,
                        'group_c_nighttime_work_hour': 54,
                        'group_c_holiday_work_hour': 0,
                        'group_d_general_work_hour': 165,
                        'group_d_daytime_work_hour': 109,
                        'group_d_nighttime_work_hour': 56,
                        'group_d_holiday_work_hour': 0,
                    },
                    {
                        'year': years[2023],
                        'month': months[9],
                        'monthly_work_hour': 168,
                        'group_a_general_work_hour': 165,
                        'group_a_daytime_work_hour': 116,
                        'group_a_nighttime_work_hour': 49,
                        'group_a_holiday_work_hour': 0,
                        'group_b_general_work_hour': 162,
                        'group_b_daytime_work_hour': 108,
                        'group_b_nighttime_work_hour': 54,
                        'group_b_holiday_work_hour': 0,
                        'group_c_general_work_hour': 165,
                        'group_c_daytime_work_hour': 109,
                        'group_c_nighttime_work_hour': 56,
                        'group_c_holiday_work_hour': 0,
                        'group_d_general_work_hour': 168,
                        'group_d_daytime_work_hour': 117,
                        'group_d_nighttime_work_hour': 51,
                        'group_d_holiday_work_hour': 0,
                    },
                    {
                        'year': years[2023],
                        'month': months[10],
                        'monthly_work_hour': 176,
                        'group_a_general_work_hour': 165,
                        'group_a_daytime_work_hour': 109,
                        'group_a_nighttime_work_hour': 56,
                        'group_a_holiday_work_hour': 0,
                        'group_b_general_work_hour': 176,
                        'group_b_daytime_work_hour': 120,
                        'group_b_nighttime_work_hour': 56,
                        'group_b_holiday_work_hour': 0,
                        'group_c_general_work_hour': 168,
                        'group_c_daytime_work_hour': 117,
                        'group_c_nighttime_work_hour': 51,
                        'group_c_holiday_work_hour': 0,
                        'group_d_general_work_hour': 173,
                        'group_d_daytime_work_hour': 119,
                        'group_d_nighttime_work_hour': 54,
                        'group_d_holiday_work_hour': 0,
                    },
                    {
                        'year': years[2023],
                        'month': months[11],
                        'monthly_work_hour': 159,
                        'group_a_general_work_hour': 168,
                        'group_a_daytime_work_hour': 117,
                        'group_a_nighttime_work_hour': 51,
                        'group_a_holiday_work_hour': 2,
                        'group_b_general_work_hour': 165,
                        'group_b_daytime_work_hour': 116,
                        'group_b_nighttime_work_hour': 49,
                        'group_b_holiday_work_hour': 2,
                        'group_c_general_work_hour': 162,
                        'group_c_daytime_work_hour': 108,
                        'group_c_nighttime_work_hour': 54,
                        'group_c_holiday_work_hour': 8,
                        'group_d_general_work_hour': 165,
                        'group_d_daytime_work_hour': 109,
                        'group_d_nighttime_work_hour': 56,
                        'group_d_holiday_work_hour': 8,
                    },
                    {
                        'year': years[2023],
                        'month': months[12],
                        'monthly_work_hour': 168,
                        'group_a_general_work_hour': 173,
                        'group_a_daytime_work_hour': 119,
                        'group_a_nighttime_work_hour': 54,
                        'group_a_holiday_work_hour': 0,
                        'group_b_general_work_hour': 165,
                        'group_b_daytime_work_hour': 109,
                        'group_b_nighttime_work_hour': 56,
                        'group_b_holiday_work_hour': 0,
                        'group_c_general_work_hour': 176,
                        'group_c_daytime_work_hour': 120,
                        'group_c_nighttime_work_hour': 56,
                        'group_c_holiday_work_hour': 0,
                        'group_d_general_work_hour': 168,
                        'group_d_daytime_work_hour': 117,
                        'group_d_nighttime_work_hour': 51,
                        'group_d_holiday_work_hour': 0,
                    },
                ]

                try:
                    with transaction.atomic():
                        WorkCalendar.objects.bulk_create([WorkCalendar(**entry) for entry in data])
                    self.stdout.write(self.style.SUCCESS('WorkCalendar modeli melumatlari ugurla elave edildi.'))
                except Exception as e:
                    self.stdout.write(self.style.ERROR(f'Xeta bash verdi: {str(e)}'))
            else:
                self.stdout.write(self.style.WARNING('Melumat elave olunmadi!!! Elave edilecek ay ve ya il yoxdur.'))
        else:
            self.stdout.write(self.style.WARNING('Melumat elave olunmadi!!! Melumat elave oluna bilmeyi uchun WorkCalendar modeli bosh olmalidir.'))